version: '2'
services:
    countrycodelookup-app:
        image: countrycodelookup
        external_links:
            - countrycodelookup-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/CountryCodeLookup
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    countrycodelookup-postgresql:
        extends:
            file: postgresql.yml
            service: countrycodelookup-postgresql
